apiVersion: apps/v1
kind: Deployment
metadata:
  name: secops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secops
  template:
    metadata:
      labels:
        app: secops
    spec:
      containers:
      - name: secops
        imagePullPolicy: Always
        image: 10.10.10.245:5005/root/gitlab-ci-k8s-demo/nginxt:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: secops
  labels:
    run: secops
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: secops
  type: NodePort
